### ISSUE TITLE
Version 15 is broken: it does not compute next tag

### ISSUE THREAD

**Issue by DavidLe-earnin** [craig-day/compute-tag#17]
craig-day/compute-tag@v15
  with:
    github_token: ***
    version_scheme: semantic
    version_type: patch
    tag_fetch_depth: 10
    prerelease_suffix: beta
    
Fetching tags.
Computing the next tag based on: v1.0.11
Computed the next tag as: v1.0.11

**Comment by craig-day** [comment]
This should be resolved via #18
