### ISSUE TITLE
Not generating the new tag

### ISSUE THREAD

**Issue by hishd** [craig-day/compute-tag#19]
The version v15 failed generating the new tag based on the previous tag.

Output:
with:
    github_token: ***
    version_scheme: continuous
    version_type: patch
    tag_fetch_depth: 10
    prerelease_suffix: beta

**Comment by jizhang27** [comment]
should be fixed by #18, @craig-day any plans to merge the patch?

**Comment by Zendesk-JeffreyCai** [comment]
Cool, nice to see this been merged.
May I ask when will we have v16 release? thank you @craig-day @Frederick888  🙇
