### ISSUE TITLE
prerelease_suffix not applied

### ISSUE THREAD

**Issue by rbury** [craig-day/compute-tag#3]
As demonstrated in the log below, the command was run with prerelease_suffix of 'beta', but the suffix used in the computed tag is 'alpha'.

##[group]Run craig-day/compute-tag@08233c8e763aa357c7930adf553f5b2cd8d29d1b
 with:
   github_token: ***
   version_scheme: semantic
   version_type: prerelease
   **prerelease_suffix: beta**
 env:
   GITHUB_TOKEN: ***
 ##[endgroup]
 Computing the next tag based on: v0.1.0-alpha.5
 Computed the next tag as: v0.1.0-**alpha**.6

**Comment by rbury** [comment]
Sorry I'm not familiar with js
It seems like it's checking for an existing prerelease tag and returning the existing tag if one exists.
function determinePrereleaseName(semTag) ?

If this is correct, I would expect it to use an existing tag over the default, but only if one has not been specified with prerelease_suffix.

In this case I'm assuming to change the prerelease suffix would require manually tagging with the new suffix. However I would suggest the behavior would be better to consider a specified suffix as the most authoritative.

**Comment by craig-day** [comment]
Resolved in #4
