### ISSUE TITLE
Computed initial semver tag is invalid

### ISSUE THREAD

**Issue by mlovic-earnin** [craig-day/compute-tag#9]
Hi. I'm using the action on a new repo with no existing tags, and it's computing the following tag:

```Run craig-day/compute-tag@v13
Fetching existing tags. This may take a while on large repositories.
Tags fetch complete.
Computed the next tag as: v1.0.0.0
```

I would expect to see `v1.0.0`, or something with 3 numbers. AFAIK having 4 numbers is not valid semver.

The code seems to be appending an extra zero to all initial tags:

https://github.com/craig-day/compute-tag/blob/f621c5c68f308e49b10cd840d40301b8aead0349/action.js#L52

In case this is the intended behavior, can you explain why?

**Comment by craig-day** [comment]
Hello and sorry this issue was missed. No, I don't think this is intended. Either this function or its callers are doing the wrong thing.
